### ISSUE TITLE
Either default to non-regex search, or escape the pattern

### ISSUE THREAD

**Issue by rrthomas** [kopoli/helm-grepint#18]
If I type `C-c G` and the symbol at point is `.label`, then this is what is searched for. Only, because it is a regex search, anything matching `.label` as a regex is displayed. This is not what I expect!

I can see two obvious options here: either default to non-regex search (i.e. escape the search pattern under the hood); this would need some work, I guess, as by default `helm-grepint` expects to always do a regex search; or, when the pattern is supplied from the buffer, escape it (this might be slightly confusing to look at, but only in languages that use regex special characters in identifiers).

**Comment by kopoli** [comment]
It seems that the string under point (`thing-at-point`) is usually interpreted in different helm grep interfaces in the following way:

- From helm proper, both `helm-grep-do-git-grep` and `helm-grep-do-ag` take the string as-is, giving it straight to the grep.
- `helm-git-grep`'s `helm-git-grep-at-point` behaves as above too.
- `helm-ag` most likely behaves exactly as above (I couldn't get it to work with moderate effort, but there doesn't seem to be any escaping of the input string).
- `helm-swoop` escapes the string. E.g. `.label` becomes `\.label`.

I agree with you that the correct behaviour (in my opinion) would be to search for the string-under-point verbatim. I.e. to NOT interpret the special regexp characters. IMO the best way to implement it would be to escape the string (like `helm-swoop`).

However, as most of the grep interfaces work in such a way that the special characters are NOT escaped and `helm-grepint` works already in such a manner (even though I regard that behaviour as less than correct) the default should not be changed. 

Probably a defcustom can be added to enable escaping the string at point. Currently getting the initial string is handled by `helm-grepint-pre-input-function`.

**Comment by rrthomas** [comment]
For me the key point is what happens when you pass a string at point: it should search for that string. It's interesting that I hadn't tried helm's own interfaces to git-grep. So I'd consider that a design bug in helm (though in most circumstances it won't be a problem, as identifiers won't include RE metacharacters), but still it wouldn't be good to have `helm-grepint` simply work differently by default.

I don't know whether there's a better way I could achieve the same result (that is, search a project for occurrences of a language symbol), for example by using `helm-global`.

Thanks as always for your thoughtful response! Certainly, a preference would help.

**Comment by kopoli** [comment]
Added an option to enable the regexp-quoting of the pre-input string.

**Comment by kopoli** [comment]
Whoops! forgot to merge the pending change until now.

**Comment by rrthomas** [comment]
Thanks, is there a release?

**Comment by kopoli** [comment]
Thanks for reminding! 

There is now release 1.6.0. I guess it hits MELPA stable tomorrow.

**Comment by rrthomas** [comment]
Thanks, I see it's up now!
