### ISSUE TITLE
Git backend case-sensitive by default?

### ISSUE THREAD

**Issue by MageSlayer** [kopoli/helm-grepint#2]
Hi

I am wondering if it's by design that git-grep backend is case-sensitive?
I mean:
(helm-grepint-add-grep-config git-grep
    :command "git"
    :arguments "--no-pager grep --line-number --no-color" <--- lacks -i option

ag backend has --ignore-case.

It looks like like a mismatch.

Or maybe it is a good idea to implement/support "smart" case (ignore case unless some uppercase symbol found)?

**Comment by kopoli** [comment]
Hi,

Thank you for reporting this. 

It is indeed an oversight that the git-grep is missing the --ignore-case argument. I pushed 60669289722b5849565472d91753ba0a705c1178 that adds the missing argument and therefore makes the git-grep and ag behaviours consistent.

The idea of supporting a "smart case" behaviour is excellent. I'll look into adding such behaviour. The original helm-grep seems to support such option and making this behave similarly would be very good.

**Comment by MageSlayer** [comment]
Thanks.
Yeap, I also think "smart case" will be a valuable addition.
