### ISSUE TITLE
Cannot cycle case sensitivity

### ISSUE THREAD

**Issue by rrthomas** [kopoli/helm-grepint#20]
When I press `M-c` during helm-grepint, nothing happens. (I looked at the source and see that `helm-grepint-helm-map` also binds `<right>`, and that seems to do nothing either.)

This appears to be because the `:keymap` keyword of `helm` is obsolete (according to the documentation), and the keymap should be attached to the source instead. Indeed, if I move the `:keymap` entry to `helm-grepint-helm-source`, then it works as expected.

**Comment by kopoli** [comment]
Thanks for testing this! 

It's like I haven't used much of this functionality for years :sweat_smile:.

I reproduced the problem and the fix as you described. Would you like to make the change as you found this ?
