### ISSUE TITLE
Stable releases on MELPA stable?

### ISSUE THREAD

**Issue by rrthomas** [kopoli/helm-grepint#7]
I see that frequent date releases are made (great!); would it be possible also to have stable "version number" releases on MELPA stable?

**Comment by kopoli** [comment]
That would be a good addition.

I need to brush up on what needs to be done to get the package accepted to the stable MELPA. I haven't run any linting to the package for a long time.

**Comment by rrthomas** [comment]
Good, thanks!

**Comment by kopoli** [comment]
It appears that only thing that was needed for melpa-stable was that the repository should have tags that conform to `version-to-list` function:

https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#making-your-package-ready-for-inclusion

I.e. usually I add `v` prefix to the version tag, but when that was removed, a stable version was generated:

https://stable.melpa.org/#/helm-grepint

**Comment by rrthomas** [comment]
Fantastic, got it!
