### ISSUE TITLE
Equivalent of `helm-grep-save-results`?

### ISSUE THREAD

**Issue by rrthomas** [kopoli/helm-grepint#8]
Sorry if I've misunderstood something here about helm, as it's only recently I've been using it more than superficially.

I would like with `helm-grepint` to save results for eyeballing and later use in a persistent buffer. With the built-in grep support, the solution seems to be `helm-grep-save-results`. I don't see anything similar in `helm-grepint`; have I overlooked something?

**Comment by kopoli** [comment]
There is the `helm-grepint-grep-action-mode` which is the second action when helm is enabled (the first action is jumping to the specific file and line). The second action can be triggered e.g. with `F2`. This creates a new `grep-mode` buffer of the current contents of the helm window. 

Unfortunately I haven't used it that much so there might be rough edges. At least one problem might be that it names the buffer as `* grep-mode <buffer-name>*` where the name of the buffer where the `helm-grepint` was started (that most likely has very little to do with the actual contents of the grepping).

**Comment by rrthomas** [comment]
Thanks! Sorry, it seems it's just my being unfamiliar with helm that is the problem here. I shall let you know if I find any issues, of course.
