### ISSUE TITLE
In `helm-grepint-grep-action-mode`, refresh should be bound to grep, not compile

### ISSUE THREAD

**Issue by rrthomas** [kopoli/helm-grepint#9]
In `helm-grepint` I press `F2` to get a `grep-mode` buffer, and this works nicely. However, if I try to refresh the buffer with `g` (`recompile`), it actually runs a compile command rather than the grep command as expected. As usual, sorry if I misunderstood something about the way this sort of thing works with helm/helm-grepint.

**Comment by kopoli** [comment]
You're absolutely right that if a grep-mode is started, then it should behave as grep-mode. Thanks for reporting this.

I'll look into if there are any other expected behaviours of this kind of modes. I see that an equivalent is the third action (`F3`) of `helm-do-git-grep` and giving `g` indeed refreshes the buffer properly.

**Comment by kopoli** [comment]
The linked change actually runs the command in grep-mode when the `F2` is pressed. This has the following effects:

- Running the grep command under helm has a limiter. In grep-mode there is none.
- The command is now run through a shell. I haven't tested this in Windows, so there might be some surprises.
- The refresh (`g`) now works.

Now that I think of it, actually running grep-mode is probably better in the long run, than just faking it (as it was done previously).

**Comment by rrthomas** [comment]
Thanks so much for implementing this so fast; it seems to work fine.
